comprimento=float(input("digite o valor do comprimento: "))
altura=float(input("digite o valor da altura: "))
area= (2* comprimento + altura * 2 )
print("A area é ", area)
perimetro=(altura + comprimento )
print("O perimetro é ", perimetro)